services:

  # Base de datos MySQL	
  patitas-suite-mysql-db:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    container_name: patitas-suite-mysql-db-container
    user: 999:999
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_MYSQL_PORT_PUBLIC}:3306
    volumes:
      - patitas-suite-mysql-data:/var/lib/mysql
      #- ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      patitas-suite-network:
        ipv4_address: 173.21.0.250
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      timeout: 3s # Aumentar tiempo de espera inicial #Espera inicial antes de comenzar a comprobar(Dar tiempo a MySQL inicie)

  mysql-adminer-bd:
    image: adminer
    container_name: mysql-adminer-bd-container
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - patitas-suite-mysql-db
    networks:
      patitas-suite-network:
        ipv4_address: 173.21.0.253


networks:
  patitas-suite-network:
    driver: bridge
    #driver_opts:
    #    parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 173.21.0.0/24

volumes:
  patitas-suite-mysql-data:
    name: patitas-suite-mysql-data-local
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_MYSQL_DATA_DIR_BD}
      o: bind
