-- ========================================
-- Tabla: PERMISSION (ID, RESOURCE, ACTION)
-- ========================================

INSERT INTO PERMISO (ID, RESOURCE, ACTION) VALUES (1, '/admin/usuarioList.xhtml', 'ALL');
INSERT INTO PERMISO (ID, RESOURCE, ACTION) VALUES (2, '/admin/usuarioList.xhtml', 'READ');
INSERT INTO PERMISO (ID, RESOURCE, ACTION) VALUES (3, '/admin/usuarioList.xhtml', 'WRITE');
INSERT INTO PERMISO (ID, RESOURCE, ACTION) VALUES (4, '/admin/usuarioList.xhtml', 'DELETE');

INSERT INTO PERMISO (ID, RESOURCE, ACTION) VALUES (5, '/recepcionista/mascota.xhtml', 'ALL');
INSERT INTO PERMISO (ID, RESOURCE, ACTION) VALUES (6, '/recepcionista/mascota.xhtml', 'READ');
INSERT INTO PERMISO (ID, RESOURCE, ACTION) VALUES (7, '/recepcionista/mascota.xhtml', 'WRITE');

INSERT INTO PERMISO (ID, RESOURCE, ACTION) VALUES (8, '/empleado/tareas.xhtml', 'READ');
INSERT INTO PERMISO (ID, RESOURCE, ACTION) VALUES (9, '/empleado/tareas.xhtml', 'WRITE');

INSERT INTO PERMISO (ID, RESOURCE, ACTION) VALUES (10, '/veterinario/fichaMedica.xhtml', 'READ');
INSERT INTO PERMISO (ID, RESOURCE, ACTION) VALUES (11, '/veterinario/fichaMedica.xhtml', 'WRITE');

INSERT INTO PERMISO (ID, RESOURCE, ACTION) VALUES (12, '/cliente/registro.xhtml', 'WRITE');
INSERT INTO PERMISO (ID, RESOURCE, ACTION) VALUES (13, '/cliente/registro.xhtml', 'READ');

-- =========================
-- Tabla: ROLE (ID, NAME)
-- =========================

INSERT INTO ROL (ID, NAME) VALUES (1, 'ADMIN');
INSERT INTO ROL (ID, NAME) VALUES (2, 'RECEPCIONISTA');
INSERT INTO ROL (ID, NAME) VALUES (3, 'EMPLEADO');
INSERT INTO ROL (ID, NAME) VALUES (4, 'VETERINARIO');

-- ============================
-- Tabla: USER (ID, NAME, PASSWORD)
-- ============================

-- Contraseña ya encriptada (reemplaza con el resultado de tu encriptador AES Base64, por ejemplo "admin123")
INSERT INTO USER (ID, NAME, PASSWORD) VALUES (1, 'admin', 'uVQoLxtZvlhBuamIlWRLGQ==');

-- ================================
-- Enlace USER_ROL
-- ================================

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);

-- ================================
-- Tabla de relaciones ROL_PERMISO
-- (Esto depende del alcance de cada rol)
-- ================================

-- ADMIN con todo acceso
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 1);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 4);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 5);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 6);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 7);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 8);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 9);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 10);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 11);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (1, 13);

-- RECEPCIONISTA: gestiona mascotas y clientes
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (2, 5);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (2, 6);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (2, 7);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (2, 12);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (2, 13);

-- EMPLEADO: ve y marca tareas
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (3, 8);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (3, 9);

-- VETERINARIO: acceso a ficha médica
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (4, 10);
INSERT INTO ROLE_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (4, 11);

COMMIT;
