-- =========================
-- Tabla: ROL (ID, NOMBRE)
-- =========================

INSERT INTO ROL (ID, NOMBRE) VALUES (1, 'ADMINISTRADOR');
INSERT INTO ROL (ID, NOMBRE) VALUES (2, 'RECEPCIONISTA');
INSERT INTO ROL (ID, NOMBRE) VALUES (3, 'EMPLEADO');
INSERT INTO ROL (ID, NOMBRE) VALUES (4, 'VETERINARIO');

-- ===========================================
-- Tabla: USUARIO (ID, USERNAME, NOMBRECOMPLETO, CORREO, CLAVE, PRIMERINGRESO, rol_id)
-- ===========================================

INSERT INTO USUARIO (ID,ACTIVO,CLAVE,CORREO, NOMBRECOMPLETO,  PRIMERINGRESO,USERNAME, rol_id)
VALUES (1,1, 'uVQoLxtZvlhBuamIlWRLGQ==','admin@patitas.com', 'Miguel Armas',1, 'migueladm',1);
INSERT INTO USUARIO (ID,ACTIVO,CLAVE,CORREO, NOMBRECOMPLETO,  PRIMERINGRESO,USERNAME, rol_id)
VALUES (2,1, 'uVQoLxtZvlhBuamIlWRLGQ==','dome_a@patitas.com', 'Domenica Rojas',1, 'domenica',2);
INSERT INTO USUARIO (ID,ACTIVO,CLAVE,CORREO, NOMBRECOMPLETO,  PRIMERINGRESO,USERNAME, rol_id)
VALUES (3,1, 'uVQoLxtZvlhBuamIlWRLGQ==','victor_r@patitas.com', 'Victor Roa',1, 'victor',3);

-- ==============================================
-- Tabla: HABITACION (ID, CAPACIDAD, ESTADO, TIPO, mascota_actual_id)
-- ==============================================

INSERT INTO HABITACION (ID, CAPACIDAD, ESTADO, TIPO, mascota_actual_id)
VALUES (1, 1, 'LIBRE', 'INDIVIDUAL', NULL);

INSERT INTO HABITACION (ID, CAPACIDAD, ESTADO, TIPO, mascota_actual_id)
VALUES (2, 1, 'OCUPADA', 'INDIVIDUAL', NULL);

INSERT INTO TIPODETAREA (ID, DESCRIPCION, NOMBRE)
VALUES (1, 'DAR DE COMER A LA MASCOTA', 'ALIMENTAR');

INSERT INTO TIPODETAREA (ID, DESCRIPCION, NOMBRE)
VALUES (2, 'JUGAR CON LA MASCOTA', 'JUGAR');

INSERT INTO TIPODETAREA (ID, DESCRIPCION, NOMBRE)
VALUES (3, 'ASEAR LA HABITACION DE LA MASCOTA', 'ASEAR');
